version: '3.8'

networks:
  backend:

services:

  backend:
    command: ["pipenv", "run", "uvicorn", "main:app", "--port", "5000", "--reload", "--host", "0.0.0.0","--log-level", "debug"]
  
  reverseproxy:
    build:
      context: ./reverseproxy/development
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Development
        BACKEND_PORT: ${REVERSEPROXY_PORT}
        BACKEND_HOST: ${REVERSEPROXY_HOST}
        BACKEND_PROTOCOL: ${REVERSEPROXY_PROTOCOL}
        BACKEND_PREFIX: ${REVERSEPROXY_PREFIX}

volumes:
  postgres_data:
    name: postgres_data
