version: '3.8'

services:
  database:
    container_name: database
    restart: always
    image: theeliteoneshot/website-database:latest
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: theeliteoneshot/website-backend:latest
    restart: always
    ports:
      - ${BACKEND_PORT}:5000
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - database

volumes:
  postgres_data:
    name: postgres_data
