version: '3.8'

networks:
  backend:

services:

  database:
    container_name: database
    restart: always
    image: theeliteoneshot/website-database:latest
    networks:
      - backend
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      # Store the database data inside the linux container. This should only clear upon an environment rebuild. SSH in to the container to export/import data.
    volumes:
      - /database_data/:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: theeliteoneshot/website-backend:latest
    restart: always
    networks:
      - backend
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - database
 
  reverseproxy:
    container_name: reverseproxy
    restart: always
    image: theeliteoneshot/website-reverseproxy:latest
    networks:
      - backend
    environment:
      ORIGIN_DOMAIN: ${ORIGIN_DOMAIN}
      ORIGIN_ALLOW_METHOD: ${ORIGIN_ALLOW_METHOD}
      ORIGIN_ALLOW_CREDENTIALS: ${ORIGIN_ALLOW_CREDENTIALS}
    ports:
      - ${REVERSEPROXY_PORT}:80
    depends_on:
      - backend