version: '3.8'

services:
  frontend:
    container_name: frontend
    image: theeliteoneshot/website-frontend:latest
    ports:
      - ${FRONTEND_PORT}:5000
    environment:
      ORIGIN_DOMAIN: ${ORIGIN_DOMAIN}